### PR TITLE
User custom configuration

### PR DESCRIPTION
**Pull request by TheoBrigitte**
Towards: https://github.com/giantswarm/giantswarm/issues/4452

Prepare CoreDNS helm chart for chart-operator to be able to configure it using user specific configmap.

### CODE REVIEW

**Review by kopiczko — APPROVED** [review]
LGTM

**Review by puja108 — COMMENTED** [review]
cache templating might need changes

**Review by indyfree — APPROVED** [review]
LGTM. Documenting how to use the templating, espacially if they are not defaulted in `values.yaml` should be done. Maybe in the Readme?

I don't know about the dns details here, but maybe we can have a helm test for these?

**Comment by indyfree** [comment]
FYI, updating with current master branch allows you to reference `wip-SHA` (which is permanent, `SHA-basic` is for e2e test and gets deleted after a run) here: https://github.com/giantswarm/cluster-operator/blob/d0bde23758262a5076fef1a66296004914bc92cd/service/controller/aws/v8/key/key.go#L17

**Comment by TheoBrigitte** [comment]
Here is an example of what the `secret/coredns-user-values` looks like

```
apiVersion: v1
data:
  additionalProxies:
    - proxy foo.com 1.1.1.1
    - proxy bar.com 8.8.8.8
  cache: |
    cache 60 {
          success 524288
          denial 524288
          prefetch 10000
        }
kind: ConfigMap
metadata:
  labels:
    app: coredns
    cluster-operator.giantswarm.io/configmap-type: user
    giantswarm.io/cluster: 5isqs
    giantswarm.io/managed-by: cluster-operator
    giantswarm.io/organization: giantswarm
    giantswarm.io/service-type: managed
  name: coredns-user-values
```

**Pull request merged**
