### PR TITLE
Move eviction to annotation

### PR DESCRIPTION
**Pull request by MarcelMue**
towards https://github.com/giantswarm/giantswarm/pull/2206

Discussion: https://gigantic.slack.com/archives/C2MS2VB37/p1548690903001700

### CODE REVIEW

**Review by marians — APPROVED** [review]

**Review by tuommaki — APPROVED** [review]
:+1:

**Review by calvix — APPROVED** [review]
:trollface: wow

**Comment by MarcelMue** [comment]
@rossf7 Is this safe to merge without changing the version/channel? Or will we get into a weird state? I can't remember if there was any danger to doing this.

**Review by rossf7 — APPROVED** [review]
LGTM and good catch on needing the annotation.

For deploying if you don't change the version chart-operator will reconcile it when you merge. That is because the SHA is templated in Chart.yaml. 

`version: 0.2.3-[[ .SHA ]]`

If you change the minor version you can link the deployment to a release in cluster-operator. That is for major changes. If this is fine in testing I don't think that's necessary.

**Comment by MarcelMue** [comment]
I tested this on `gauss` and it's working fine.

**Pull request merged**
