### PR TITLE
Add SHA to version

### PR DESCRIPTION
**Pull request by indyfree**
Towards https://github.com/giantswarm/giantswarm/issues/4078, https://github.com/giantswarm/giantswarm/issues/4441

### CODE REVIEW

**Comment by puja108** [comment]
do we need to sync this with @TheoBrigitte's PRs/changes?

**Comment by indyfree** [comment]
https://github.com/giantswarm/cluster-operator/pull/308 isn't merged yet, so this won't be rolled out to customer clusters before then.
Theoretically it doesn't matter if we merge it before or after, but to reduce potential friction, would be good to merge this before. WDYT @TheoBrigitte ?

**Comment by TheoBrigitte** [comment]
I do not see an issue by merging this before the cluster-operator PR.

**Comment by indyfree** [comment]
Cool, I'd need an approval then :)

**Review by TheoBrigitte — APPROVED** [review]

**Pull request merged**
