### PR TITLE
Tell autoscaler that the pod is safe to evict

### PR DESCRIPTION
**Pull request by MarcelMue**
This is so that the `cluster-autoscaler` actually scales down a node when only our workload is remaining.
In small nodes (e.g. m3.large) our own workload might make up more than 50% of the nodes workload and will therefor never be scaled down. This annotation is only for the autoscaler to only consider "real" workload.

More reading: https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/FAQ.md#what-types-of-pods-can-prevent-ca-from-removing-a-node

towards https://github.com/giantswarm/giantswarm/issues/4543

### CODE REVIEW

**Comment by MarcelMue** [comment]
Also cc @pipo02mix this might be interesting for our customers as well which have custom configs right now.

**Review by teemow — APPROVED** [review]

**Review by rossf7 — APPROVED** [review]
LGTM and change is nice.

For deployment, unless its been fixed you'll need to bump the chart versions if you want chart-operator to reconcile this.

This is easy to miss and a weakness of the current release channels approach.

**Review by pipo02mix — APPROVED** [review]
LGTM

**Comment by xh3b4sd** [comment]
Do we track the failing e2e test somewhere?

**Comment by MarcelMue** [comment]
It's a valid fail - I just asked about it here: https://gigantic.slack.com/archives/C2MS2VB37/p1544805479037400

**Comment by MarcelMue** [comment]
E2E is finally clean, just needed to update the vendor and clean up a little bit :tada:

**Review by tuommaki — APPROVED** [review]

**Review by rossf7 — APPROVED** [review]

**Review by pipo02mix — APPROVED** [review]
LGTM

**Pull request merged**
