### PR TITLE
log failing requests

### PR DESCRIPTION
**Pull request by TheoBrigitte**
Towards: https://github.com/giantswarm/giantswarm/issues/4482

CoreDNS currently only log error but not failing requests.

There is a performance penalty when using the log plugin, but as we only log `denial` and `error` it should be mitigated.

see https://coredns.io/plugins/log/#syntax

### CODE REVIEW

**Review by tuommaki — APPROVED** [review]
LGTM

When this is deployed to larger clusters, would it make sense to monitor (i.e. by human looking into graphs) resource usage a bit for a while?

**Review by MarcelMue — APPROVED** [review]
LGTM

**Comment by indyfree** [comment]
Please increment the version in `Chart.yaml` and push the current master to the `0.1.20` release. See also https://github.com/giantswarm/giantswarm/issues/4078

**Comment by TheoBrigitte** [comment]
> When this is deployed to larger clusters, would it make sense to monitor (i.e. by human looking into graphs) resource usage a bit for a while?

Do you mean looking into coredns pods resource consumption to denote if there is any significant difference ?

**Pull request merged**
