### PR TITLE
Make log plugin verbosity configurable

### PR DESCRIPTION
**Pull request by pipo02mix**
Make log plugin verbosity configurable

### CODE REVIEW

**Review by rossf7 — APPROVED** [review]

**Comment by rossf7** [comment]
But CI looks borked :(

**Comment by pipo02mix** [comment]
Change format to string for `log` property, in the user values config map needs to be done  string so it has the sense to have coherence

**Comment by pipo02mix** [comment]
The tests are passing but the status here it is not updated 🤷‍♂

**Review by rossf7 — APPROVED** [review]
LGTM. Super weird about CI but I'd say let's merge it. 

Also a bit off topic but we should have a Circle badge on the README.

**Pull request merged**
